### ISSUE TITLE
How to enable after installation?

### ISSUE THREAD

**Issue by BebeMischa** [ben8p/lovelace-auto-reload-card#1]
Hello,

I'm happy seeing this, as i'm affected by the refresh problems using two wallmounted tablets at my home. Thank you for this usefull tool.

I'm sorry for this beginner question, but i can't find the needed info anywhere.

I just installed this using HACS. That wen't fine. I can see it in the repository.
But i can't find, how do i edit/enable it.

Can you help me please?

**Comment by ben8p** [comment]
Hi,

From HACS you should be able to select and install the custom card.  

Once done, you need to go to the dashboard your are displaying on your wallmounted tablets.
enter the edit mode, add a card (of manual type) and put the following inside:
```
type: 'custom:auto-reload-card'
delay_in_minute: 1
```

Replace 1 by the refresh time you want (I found 6 to work pretty fine for me).

Save and that should be it.

**Comment by BebeMischa** [comment]
Thank you for the fast response.

I did install and see it installed. Restarted HA to be sure, it is loaded.

But when attempting to add to lovelace, i see this:

![afbeelding](https://user-images.githubusercontent.com/73079275/103636247-01204b80-4f4a-11eb-9fda-734f56187407.png)

**Comment by ben8p** [comment]
When doing same on my setup, it does allow me to save (despite the error message in orange).

Is you save button getting enabled at some point?

**Comment by BebeMischa** [comment]
As you see, it was not enabled at the moment of the screenshot. I tryed now again, and it worked. It created a invisible card, only showing up, whet editing is enabled. So i think, it's ok now.
Thank you.

**Comment by ben8p** [comment]
Yes that seems all correct now!

**Comment by ben8p** [comment]
Yes that seems all correct now!

**Comment by BebeMischa** [comment]
Oh, i was a bit too fast. So it only works on all the tabs, i've created. But not on the initial tab, which has been there on installation of HA already. That's my main tab now. There i still do get the save button greyed out...

**Comment by BebeMischa** [comment]
So i tryed now to ad the card on the first tab with raw code editor, it saved, but the card is not there even when editing. I think, there is something with this initial tab, that does not allow it...

**Comment by BebeMischa** [comment]
Never mind, i founded a workaround now. Placing the card directly did not work, but placing it in a vertical stack did...
