### ISSUE TITLE
Device exclusion

### ISSUE THREAD

**Issue by DJAMIRSAM** [ben8p/lovelace-auto-reload-card#4]
Can you make it possible to exclude devices because it keeps reloading my screen when I'm editing and I only need it for my wall mounted tablet

**Comment by Protoncek** [comment]
Exactly the same problem... i have it set to 60 minutes, so it can destroy a lot of my work. And, it seems that when this card is placed in one lovelace it refreshes all lovelace panels. So, any type of exclusion would be great.

**Comment by DJAMIRSAM** [comment]
I found that creating a new Lovelace section that only the tablet has access to works the best but recently it has stopped working for me I think
